#!/usr/bin/env python

import os
import sys

dict = {}


def letters(input):
    valids = ""
    for character in input:
        if character.isalpha() or character == " ":
            valids += character
    return valids

for line in sys.stdin:
    line = line.strip()
    line = line.lower()
    line = letters(line)
    line_split = line.split()
    filepath = os.environ["map_input_file"]
    file_name = os.path.split(filepath)[-1]
    for word in line_split:
        if word in dict:
            index = dict.get(word)
            found = index.find(file_name)
            if (found == -1):
                dict[word] = dict[word] + " " + file_name
        else:
            dict[word] = file_name
for y in dict:
    print(y + " " + dict[y])
